
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    hostname: fhir-template
    container_name: fhir-template
#   command: --check-caps false
    ports:
      - 32782:1972
      - 32783:52773
      - 32784:53773
    command:
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
      - --check-caps false
    volumes:
      - ./data:/data
      - ./fhirUI:/usr/irissys/csp/fhirUI
      - ./:/home/irisowner/irisdev
    networks:
      - fhir-net
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE="24h"
      - OLLAMA_MAX_LOADED_MODELS=1
    networks:
      - fhir-net
    entrypoint: /bin/sh
    command: -c "ollama serve & sleep 5 && ollama pull llama3 && wait"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  streamlit:
    build: ./streamlit
    container_name: streamlit
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
    depends_on:
      - iris
      - ollama
    networks:
      - fhir-net

volumes:
  ollama:

networks:
  fhir-net:
    driver: bridge